export type Lang = "en" | "fr"

// ============================================================
// PROJECTS DATA — organized by category
// ============================================================

export type ProjectCategory = "school" | "professional" | "personal"

export const projects = [
    // ── PROFESSIONAL / INTERNSHIP ──────────────────────────────
    {
        slug: "erp-mc-sarl",
        category: "professional" as ProjectCategory,
        name: "ERP MC Sarl",
        tags: ["Laravel 12", "React", "PostgreSQL"],
        status: "In Progress",
        statusColor: "#f59e0b",
        year: "2025",
        gradient: "linear-gradient(135deg, #1a0a00 0%, #3d1a00 50%, #7c3a00 100%)",
        emoji: "⚙️",
        github: null,
        live: null,
        en: {
            desc: "Complete ERP for textile production management at MC Sarl.",
            longDesc: "A full-featured Enterprise Resource Planning system built for MC Sarl, a textile production company in Douala. Covers the entire production lifecycle from order intake to delivery, including inventory management, production scheduling, quality control, and financial reporting.",
            features: ["Order & production lifecycle management", "Real-time inventory tracking", "Production scheduling & optimization", "Quality control checkpoints", "Financial reporting & invoicing", "Commercial management module (CodeIgniter 4)"],
            challenge: "Modeling the complex textile production workflow with multiple interdependent stages while keeping the UI intuitive for non-technical staff.",
        },
        fr: {
            desc: "ERP complet pour la gestion de la production textile chez MC Sarl.",
            longDesc: "Un système ERP complet construit pour MC Sarl, une entreprise de production textile à Douala. Couvre l'ensemble du cycle de production, de la prise de commande à la livraison, incluant la gestion des stocks, la planification de la production, le contrôle qualité et les rapports financiers.",
            features: ["Gestion du cycle de vie des commandes et de la production", "Suivi des stocks en temps réel", "Planification et optimisation de la production", "Points de contrôle qualité", "Rapports financiers et facturation", "Module de gestion commerciale (CodeIgniter 4)"],
            challenge: "Modéliser le flux de production textile complexe avec plusieurs étapes interdépendantes tout en gardant l'interface intuitive pour le personnel non technique.",
        },
    },
    {
        slug: "mc-immo",
        category: "professional" as ProjectCategory,
        name: "MC IMMO",
        tags: ["PHP", "HTML/CSS", "JavaScript", "MySQL"],
        status: "Deployed",
        statusColor: "#10b981",
        year: "2025",
        gradient: "linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)",
        emoji: "🏗️",
        github: null,
        live: null,
        en: {
            desc: "Asset management system for Douala General Hospital.",
            longDesc: "MC IMMO is a comprehensive asset management platform developed for the Douala General Hospital. It enables tracking of all physical assets across departments, manages maintenance schedules, and generates detailed inventory reports. Built with PHP and vanilla JavaScript for maximum compatibility in the hospital's legacy infrastructure.",
            features: ["Complete asset lifecycle tracking", "Department-level inventory management", "Maintenance scheduling & alerts", "PDF report generation", "Role-based access control"],
            challenge: "Building a system that could run reliably on the hospital's legacy infrastructure without requiring modern server configurations.",
        },
        fr: {
            desc: "Système de gestion du patrimoine pour l'Hôpital Général de Douala.",
            longDesc: "MC IMMO est une plateforme complète de gestion du patrimoine développée pour l'Hôpital Général de Douala. Elle permet le suivi de tous les actifs physiques par département, gère les calendriers de maintenance et génère des rapports d'inventaire détaillés.",
            features: ["Suivi complet du cycle de vie des actifs", "Gestion des inventaires par département", "Planification de la maintenance et alertes", "Génération de rapports PDF", "Contrôle d'accès basé sur les rôles"],
            challenge: "Construire un système fonctionnant de manière fiable sur l'infrastructure legacy de l'hôpital.",
        },
    },
    {
        slug: "mon-compagnon-etudiant",
        category: "professional" as ProjectCategory,
        name: "Mon Compagnon Scolaire",
        tags: ["Flutter", "Dart", "PHP", "Laravel"],
        status: "Deployed",
        statusColor: "#10b981",
        year: "2024",
        gradient: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
        emoji: "📱",
        github: "https://github.com/LAPTOP237/mon_compagnon",
        live: null,
        en: {
            desc: "Mobile companion app for students. Schedules, notes, and resources.",
            longDesc: "A cross-platform mobile application designed to be the ultimate academic companion for university students. It centralizes schedules, personal notes, course resources, and deadline tracking in one clean interface. The backend is powered by a PHP API consumed by the Flutter frontend.",
            features: ["Smart schedule management", "Offline-first note taking", "Course resource library", "Deadline & exam reminders", "Cross-platform (iOS & Android)"],
            challenge: "Implementing a robust offline-first architecture with seamless sync when connectivity is restored.",
        },
        fr: {
            desc: "Application mobile compagnon pour étudiants. Emplois du temps, notes et ressources.",
            longDesc: "Une application mobile multiplateforme conçue pour être le compagnon académique ultime des étudiants universitaires. Elle centralise les emplois du temps, les notes personnelles, les ressources de cours et le suivi des délais dans une interface épurée.",
            features: ["Gestion intelligente des emplois du temps", "Prise de notes hors ligne", "Bibliothèque de ressources de cours", "Rappels de délais et d'examens", "Multiplateforme (iOS & Android)"],
            challenge: "Implémenter une architecture offline-first robuste avec une synchronisation transparente lors du rétablissement de la connexion.",
        },
    },
    {
        slug: "zanischool",
        category: "professional" as ProjectCategory,
        name: "ZaniSchool",
        tags: ["Python", "Desktop", "QtDesigner"],
        status: "Deployed",
        statusColor: "#10b981",
        year: "2024",
        gradient: "linear-gradient(135deg, #0a1a0a 0%, #0d2e0d 50%, #1a4d1a 100%)",
        emoji: "🏫",
        github: "https://github.com/LAPTOP237/zanischool_desktop",
        live: null,
        en: {
            desc: "Desktop school management application built with Flutter.",
            longDesc: "ZaniSchool is a desktop application for school management, built with Flutter for cross-platform desktop support. It handles student enrollment, grade management, attendance tracking, and administrative reporting for educational institutions.",
            features: ["Student enrollment & profiles", "Grade & attendance management", "Administrative reporting", "Cross-platform desktop (Windows/Linux/macOS)", "Offline-capable database"],
            challenge: "Adapting Flutter's mobile-first paradigm to a desktop-optimized UX with keyboard navigation and larger screen layouts.",
        },
        fr: {
            desc: "Application desktop de gestion scolaire construite avec Flutter.",
            longDesc: "ZaniSchool est une application desktop de gestion scolaire, construite avec Flutter pour le support multi-plateforme. Elle gère l'inscription des élèves, la gestion des notes, le suivi des présences et les rapports administratifs.",
            features: ["Inscription et profils des élèves", "Gestion des notes et des présences", "Rapports administratifs", "Desktop multiplateforme (Windows/Linux/macOS)", "Base de données hors ligne"],
            challenge: "Adapter le paradigme mobile-first de Flutter à une UX optimisée pour desktop avec navigation au clavier et mises en page grand écran.",
        },
    },
    {
        slug: "gestion-commercial",
        category: "professional" as ProjectCategory,
        name: "Gestion Commercial",
        tags: ["Codeigniter 4", "Template", "MySQL"],
        status: "Completed",
        statusColor: "#6b7280",
        year: "2022",
        gradient: "linear-gradient(135deg, #1a1000 0%, #3d2e00 50%, #7c5c00 100%)",
        emoji: "🛒",
        github: "https://github.com/LAPTOP237/gestion_commercial",
        live: null,
        en: {
            desc: "Commercial management system for sales and inventory tracking.",
            longDesc: "A web-based commercial management system that handles sales operations, inventory tracking, and customer management. Built as an early professional project demonstrating full-stack JavaScript capabilities.",
            features: ["Sales order management", "Inventory tracking", "Customer database", "Sales reporting", "Invoice generation"],
            challenge: "Building a complete full-stack JavaScript application from scratch as one of the first professional projects.",
        },
        fr: {
            desc: "Système de gestion commerciale pour le suivi des ventes et des stocks.",
            longDesc: "Un système de gestion commerciale web qui gère les opérations de vente, le suivi des stocks et la gestion des clients. Construit comme un projet professionnel précoce démontrant les capacités JavaScript full-stack.",
            features: ["Gestion des commandes de vente", "Suivi des stocks", "Base de données clients", "Rapports de ventes", "Génération de factures"],
            challenge: "Construire une application JavaScript full-stack complète de zéro comme l'un des premiers projets professionnels.",
        },
    },

    // ── SCHOOL PROJECTS ────────────────────────────────────────
    {
        slug: "myenspd-docs",
        category: "school" as ProjectCategory,
        name: "MyENSPD Docs",
        tags: ["Next.js", "JavaScript", "Python", "FastAPI"],
        status: "Deployed",
        statusColor: "#3b82f6",
        year: "2025",
        gradient: "linear-gradient(135deg, #0f2027 0%, #1a3a4d 50%, #2c5364 100%)",
        emoji: "📚",
        github: "https://github.com/LAPTOP237/myenspd-docs-frontend",
        live: "https://myenspd-docs-frontend.vercel.app",
        en: {
            desc: "Document management platform for ENSPD university students.",
            longDesc: "MyENSPD Docs is a full-stack document management platform for ENSPD university. The frontend is built with Next.js and deployed on Vercel, while the backend uses Python/FastAPI. Students can upload, search, and access academic documents, theses, and course materials.",
            features: ["Document upload & management", "Full-text search", "Academic resource library", "User authentication", "Vercel deployment"],
            challenge: "Designing a scalable document storage and retrieval system that handles large PDF files efficiently.",
        },
        fr: {
            desc: "Plateforme de gestion de documents pour les étudiants de l'ENSPD.",
            longDesc: "MyENSPD Docs est une plateforme full-stack de gestion de documents pour l'université ENSPD. Le frontend est construit avec Next.js et déployé sur Vercel, tandis que le backend utilise Python/FastAPI. Les étudiants peuvent télécharger, rechercher et accéder aux documents académiques.",
            features: ["Téléchargement et gestion de documents", "Recherche plein texte", "Bibliothèque de ressources académiques", "Authentification utilisateur", "Déploiement Vercel"],
            challenge: "Concevoir un système de stockage et de récupération de documents évolutif qui gère efficacement les grands fichiers PDF.",
        },
    },
    {
        slug: "lexa",
        category: "school" as ProjectCategory,
        name: "Lexa",
        tags: ["Flutter", "Dart", "LibreTranslate", "API"],
        status: "Completed",
        statusColor: "#a855f7",
        year: "2025",
        gradient: "linear-gradient(135deg, #1a0a2e 0%, #2e1a4d 50%, #4d1a7c 100%)",
        emoji: "🌐",
        github: "https://github.com/LAPTOP237/lexa",
        live: null,
        en: {
            desc: "Flutter translation app powered by LibreTranslate API.",
            longDesc: "Lexa is a mobile translation application built with Flutter that leverages the LibreTranslate open-source API. It supports multiple languages with a clean, intuitive interface, offline history, and real-time translation as you type.",
            features: ["Multi-language translation", "Real-time translation", "Translation history", "Offline mode for saved translations", "Clean minimal UI"],
            challenge: "Integrating a self-hosted LibreTranslate instance and handling API rate limiting gracefully in the mobile app.",
        },
        fr: {
            desc: "Application de traduction Flutter propulsée par l'API LibreTranslate.",
            longDesc: "Lexa est une application mobile de traduction construite avec Flutter qui exploite l'API open-source LibreTranslate. Elle supporte plusieurs langues avec une interface épurée et intuitive, un historique hors ligne et une traduction en temps réel.",
            features: ["Traduction multilingue", "Traduction en temps réel", "Historique des traductions", "Mode hors ligne pour les traductions sauvegardées", "Interface épurée et minimale"],
            challenge: "Intégrer une instance LibreTranslate auto-hébergée et gérer gracieusement la limitation du débit API dans l'application mobile.",
        },
    },
    {
        slug: "dal-project",
        category: "school" as ProjectCategory,
        name: "DAL Project",
        tags: ["Java", "Android", "SQLite"],
        status: "Completed",
        statusColor: "#6b7280",
        year: "2024",
        gradient: "linear-gradient(135deg, #1a0a00 0%, #2e1a00 50%, #4d3000 100%)",
        emoji: "📊",
        github: null,
        live: null,
        en: {
            desc: "Data Access Layer project — Android app with structured database architecture.",
            longDesc: "A school project focused on implementing a proper Data Access Layer pattern in an Android application. Demonstrates clean architecture principles with separation of concerns between UI, business logic, and data layers.",
            features: ["Clean DAL architecture", "SQLite database integration", "CRUD operations", "Repository pattern", "Android Material Design UI"],
            challenge: "Implementing a clean, testable data access layer that abstracts database operations from business logic.",
        },
        fr: {
            desc: "Projet DAL — Application Android avec architecture de base de données structurée.",
            longDesc: "Un projet scolaire axé sur l'implémentation d'un pattern Data Access Layer dans une application Android. Démontre les principes d'architecture propre avec séparation des préoccupations entre UI, logique métier et couches de données.",
            features: ["Architecture DAL propre", "Intégration base de données SQLite", "Opérations CRUD", "Pattern Repository", "UI Android Material Design"],
            challenge: "Implémenter une couche d'accès aux données propre et testable qui abstrait les opérations de base de données de la logique métier.",
        },
    },
    {
        slug: "cloudsimtp",
        category: "school" as ProjectCategory,
        name: "CloudSimTP",
        tags: ["Java", "CloudSim", "Cloud Computing"],
        status: "Completed",
        statusColor: "#6b7280",
        year: "2025",
        gradient: "linear-gradient(135deg, #0a0a1a 0%, #0d1a2e 50%, #1a2e4d 100%)",
        emoji: "☁️",
        github: "https://github.com/LAPTOP237/CloudSimTP",
        live: null,
        en: {
            desc: "Cloud computing simulation TP using CloudSim framework.",
            longDesc: "A practical work project for the Cloud Computing course at ENSPD. Uses the CloudSim Java framework to simulate cloud environments, virtual machine allocation, and resource scheduling algorithms. Includes documentation and practical exercises.",
            features: ["VM allocation simulation", "Resource scheduling algorithms", "Cloud environment modeling", "Performance metrics analysis", "Practical exercises & documentation"],
            challenge: "Understanding and implementing complex cloud resource scheduling algorithms within the CloudSim simulation framework.",
        },
        fr: {
            desc: "TP de simulation de cloud computing avec le framework CloudSim.",
            longDesc: "Un travail pratique pour le cours de Cloud Computing à l'ENSPD. Utilise le framework Java CloudSim pour simuler des environnements cloud, l'allocation de machines virtuelles et les algorithmes d'ordonnancement des ressources.",
            features: ["Simulation d'allocation de VM", "Algorithmes d'ordonnancement des ressources", "Modélisation d'environnement cloud", "Analyse des métriques de performance", "Exercices pratiques et documentation"],
            challenge: "Comprendre et implémenter des algorithmes complexes d'ordonnancement des ressources cloud dans le framework de simulation CloudSim.",
        },
    },
    {
        slug: "gestask",
        category: "school" as ProjectCategory,
        name: "GesTask",
        tags: ["HTML", "CSS", "JavaScript"],
        status: "Completed",
        statusColor: "#6b7280",
        year: "2023",
        gradient: "linear-gradient(135deg, #0a1a0a 0%, #1a2e1a 50%, #2e4d2e 100%)",
        emoji: "✅",
        github: "https://github.com/LAPTOP237/GesTask",
        live: null,
        en: {
            desc: "Task planner frontend built with HTML, CSS, and JavaScript.",
            longDesc: "GesTask is a simple yet functional task management application built as a school project. It demonstrates front-end development skills with vanilla HTML, CSS, and JavaScript, featuring task creation, categorization, and status tracking.",
            features: ["Task creation & management", "Category organization", "Status tracking (todo/in-progress/done)", "Local storage persistence", "Responsive design"],
            challenge: "Building a complete task management UI with vanilla JavaScript without any frameworks or libraries.",
        },
        fr: {
            desc: "Planificateur de tâches frontend construit avec HTML, CSS et JavaScript.",
            longDesc: "GesTask est une application de gestion de tâches simple mais fonctionnelle construite comme projet scolaire. Elle démontre les compétences de développement front-end avec HTML, CSS et JavaScript vanilla, avec création de tâches, catégorisation et suivi de statut.",
            features: ["Création et gestion de tâches", "Organisation par catégories", "Suivi de statut (à faire/en cours/terminé)", "Persistance en stockage local", "Design responsive"],
            challenge: "Construire une UI de gestion de tâches complète avec JavaScript vanilla sans aucun framework ni bibliothèque.",
        },
    },
    {
        slug: "biblio",
        category: "school" as ProjectCategory,
        name: "Biblio — ENSPD",
        tags: ["PHP", "MySQL", "HTML/CSS"],
        status: "Completed",
        statusColor: "#6b7280",
        year: "2024",
        gradient: "linear-gradient(135deg, #1a0a0a 0%, #2e1a1a 50%, #4d2e2e 100%)",
        emoji: "📖",
        github: "https://github.com/LAPTOP237/Biblio",
        live: null,
        en: {
            desc: "Library management system for ENSPD — books, theses, and journals.",
            longDesc: "A comprehensive library management system designed for ENSPD university. It manages the fund of books, thesis defenses, articles, and scientific magazines, as well as the lending of these resources to library members.",
            features: ["Book & resource catalog management", "Thesis and journal indexing", "Member lending system", "Search & filter capabilities", "Inventory reporting"],
            challenge: "Designing a flexible data model that accommodates different resource types (books, theses, journals) with different metadata requirements.",
        },
        fr: {
            desc: "Système de gestion de bibliothèque pour l'ENSPD — livres, mémoires et revues.",
            longDesc: "Un système complet de gestion de bibliothèque conçu pour l'université ENSPD. Il gère le fonds de livres, les mémoires de soutenance, les articles et les magazines scientifiques, ainsi que le prêt de ces ressources aux adhérents.",
            features: ["Gestion du catalogue de livres et ressources", "Indexation des mémoires et revues", "Système de prêt aux membres", "Recherche et filtrage", "Rapports d'inventaire"],
            challenge: "Concevoir un modèle de données flexible qui accommode différents types de ressources (livres, mémoires, revues) avec des exigences de métadonnées différentes.",
        },
    },

    // ── PERSONAL / GROUP PROJECTS ──────────────────────────────
    {
        slug: "ecolink",
        category: "personal" as ProjectCategory,
        name: "ECOLINK",
        tags: ["Flutter", "FastAPI", "Python", "AI"],
        status: "In Build",
        statusColor: "#10b981",
        year: "2025",
        gradient: "linear-gradient(135deg, #0d1a0d 0%, #0a2e0a 50%, #1a4d1a 100%)",
        emoji: "♻️",
        github: null,
        live: null,
        en: {
            desc: "AI-powered waste management and recycling platform.",
            longDesc: "ECOLINK is an innovative platform that uses artificial intelligence to optimize waste management and recycling in Cameroon. The mobile app allows citizens to locate recycling points, report illegal dumps, and earn rewards for eco-friendly actions. The AI backend analyzes waste images to classify them and suggest proper disposal methods.",
            features: ["AI-powered waste classification", "Interactive recycling point map", "Illegal dump reporting system", "Gamified eco-rewards", "Real-time analytics dashboard"],
            challenge: "Training a waste classification model that performs well on low-quality mobile camera images in varied lighting conditions.",
        },
        fr: {
            desc: "Plateforme de gestion des déchets et recyclage alimentée par l'IA.",
            longDesc: "ECOLINK est une plateforme innovante qui utilise l'intelligence artificielle pour optimiser la gestion des déchets et le recyclage au Cameroun. L'application mobile permet aux citoyens de localiser les points de recyclage, signaler les décharges illégales et gagner des récompenses pour leurs actions écologiques.",
            features: ["Classification des déchets par IA", "Carte interactive des points de recyclage", "Système de signalement de décharges illégales", "Récompenses écologiques gamifiées", "Tableau de bord analytique en temps réel"],
            challenge: "Entraîner un modèle de classification des déchets performant sur des images de caméra mobile de faible qualité dans des conditions d'éclairage variées.",
        },
    },
    {
        slug: "daily-learning",
        category: "personal" as ProjectCategory,
        name: "DailyLearning",
        tags: ["React", "Next.js", "TypeScript"],
        status: "In Build",
        statusColor: "#f59e0b",
        year: "2025",
        gradient: "linear-gradient(135deg, #0a0a1a 0%, #1a1a2e 50%, #2e2e4d 100%)",
        emoji: "🧠",
        github: null,
        live: null,
        en: {
            desc: "Daily learning platform with curated content and progress tracking.",
            longDesc: "DailyLearning is a personal project aimed at building a habit-based learning platform. Users receive daily curated content, track their learning streaks, and build knowledge progressively through micro-learning sessions.",
            features: ["Daily curated content delivery", "Learning streak tracking", "Progress visualization", "Topic categorization", "Bookmark & notes system"],
            challenge: "Designing an algorithm that personalizes daily content based on user interests and learning history.",
        },
        fr: {
            desc: "Plateforme d'apprentissage quotidien avec contenu curé et suivi de progression.",
            longDesc: "DailyLearning est un projet personnel visant à construire une plateforme d'apprentissage basée sur les habitudes. Les utilisateurs reçoivent du contenu curé quotidien, suivent leurs séries d'apprentissage et construisent des connaissances progressivement.",
            features: ["Livraison de contenu curé quotidien", "Suivi des séries d'apprentissage", "Visualisation de la progression", "Catégorisation par thèmes", "Système de favoris et notes"],
            challenge: "Concevoir un algorithme qui personnalise le contenu quotidien en fonction des intérêts et de l'historique d'apprentissage de l'utilisateur.",
        },
    },
    {
        slug: "cantiques-bamoun",
        category: "personal" as ProjectCategory,
        name: "Cantiques Bamouns",
        tags: ["Flutter", "Dart"],
        status: "In Build",
        statusColor: "#a855f7",
        year: "2025",
        gradient: "linear-gradient(135deg, #1a0a1a 0%, #2e1a2e 50%, #4d1a4d 100%)",
        emoji: "🎵",
        github: "https://github.com/LAPTOP237/privacy-security-for-cantique-bamoun",
        live: null,
        en: {
            desc: "Mobile app for Bamoun cultural hymns — preserving heritage through technology.",
            longDesc: "Cantiques Bamouns is a cultural preservation project that digitizes and makes accessible the traditional hymns of the Bamoun people of Cameroon. The Flutter app provides a searchable library of hymns with audio playback, lyrics, and cultural context.",
            features: ["Hymn library with search", "Audio playback", "Lyrics display with Bamoun script", "Cultural context & history", "Offline access"],
            challenge: "Digitizing and encoding Bamoun script text while ensuring accurate representation of the cultural and linguistic nuances.",
        },
        fr: {
            desc: "Application mobile pour les cantiques bamouns — préservation du patrimoine par la technologie.",
            longDesc: "Cantiques Bamouns est un projet de préservation culturelle qui numérise et rend accessibles les cantiques traditionnels du peuple Bamoun du Cameroun. L'application Flutter fournit une bibliothèque de cantiques avec lecture audio, paroles et contexte culturel.",
            features: ["Bibliothèque de cantiques avec recherche", "Lecture audio", "Affichage des paroles en écriture bamoun", "Contexte culturel et historique", "Accès hors ligne"],
            challenge: "Numériser et encoder le texte en écriture bamoun tout en assurant une représentation précise des nuances culturelles et linguistiques.",
        },
    },
]

// ============================================================
// DESIGN GALLERY DATA (Designer Mode)
// ============================================================
export const designGallery = [
    {
        category: "BRANDING",
        categoryFr: "IDENTITÉ VISUELLE",
        color: "#a855f7",
        en: { desc: "Visual identities, logos and brand systems" },
        fr: { desc: "Identités visuelles, logos et systèmes de marque" },
        items: [
            {
                name: "SIE Corporate Identity",
                nameFr: "Identité SIE",
                gradient: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
                size: "large",
                en: { desc: "Complete visual overhaul with geometric symmetry and Swiss design principles." },
                fr: { desc: "Refonte visuelle complète avec symétrie géométrique et principes du design suisse." },
                tools: ["Coreldraw","Illustrator", "Photoshop", "Lens Studio"],
            },
            {
                name: "MC Sarl Brand",
                nameFr: "Marque MC Sarl",
                gradient: "linear-gradient(135deg, #1a0a00 0%, #3d1a00 50%, #7c3a00 100%)",
                size: "small",
                en: { desc: "Logo and visual identity for a textile company." },
                fr: { desc: "Logo et identité visuelle pour une entreprise textile." },
                tools: ["CorelDraw"],
            },
            {
                name: "ECOLINK Brand",
                nameFr: "Marque ECOLINK",
                gradient: "linear-gradient(135deg, #0d1a0d 0%, #0a2e0a 50%, #1a4d1a 100%)",
                size: "small",
                en: { desc: "Eco-friendly brand identity for a recycling startup." },
                fr: { desc: "Identité de marque éco-responsable pour une startup de recyclage." },
                tools: ["Figma", "Coreldraw"],
            },
        ],
    },
    {
        category: "UI/UX",
        categoryFr: "INTERFACES",
        color: "#3b82f6",
        en: { desc: "Digital interfaces, dashboards and user experiences" },
        fr: { desc: "Interfaces numériques, tableaux de bord et expériences utilisateur" },
        items: [
            {
                name: "ERP Dashboard",
                nameFr: "Dashboard ERP",
                gradient: "linear-gradient(135deg, #0a0a1a 0%, #0d1a2e 50%, #1a2e4d 100%)",
                size: "large",
                en: { desc: "Production management dashboard with real-time KPIs and data visualization." },
                fr: { desc: "Tableau de bord de gestion de production avec KPIs en temps réel et visualisation de données." },
                tools: ["Figma"],
            },
            {
                name: "Student App UI",
                nameFr: "UI App Étudiant",
                gradient: "linear-gradient(135deg, #1a1a2e 0%, #2e1a4d 50%, #4d1a7c 100%)",
                size: "small",
                en: { desc: "Mobile UI for the student companion app." },
                fr: { desc: "Interface mobile pour l'application compagnon étudiant." },
                tools: ["Figma"],
            },
            {
                name: "Hospital Asset UI",
                nameFr: "UI Gestion Patrimoine",
                gradient: "linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)",
                size: "small",
                en: { desc: "Clean interface for hospital asset management system." },
                fr: { desc: "Interface épurée pour le système de gestion du patrimoine hospitalier." },
                tools: ["Figma"],
            },
        ],
    },
    {
        category: "PRINT",
        categoryFr: "PRINT & AFFICHES",
        color: "#f59e0b",
        en: { desc: "Posters, flyers, scarves and printed materials" },
        fr: { desc: "Affiches, flyers, foulards et supports imprimés" },
        items: [
            {
                name: "Event Posters",
                nameFr: "Affiches Événementielles",
                gradient: "linear-gradient(135deg, #2d5016 0%, #4a7c1f 50%, #c8e63c 100%)",
                size: "large",
                en: { desc: "Series of event posters for university and corporate events." },
                fr: { desc: "Série d'affiches événementielles pour des événements universitaires et d'entreprise." },
                tools: ["Corldraw"],
            },
            {
                name: "Scarves & Textiles",
                nameFr: "Foulards & Textiles",
                gradient: "linear-gradient(135deg, #4d0a2e 0%, #7c1a4d 50%, #a855f7 100%)",
                size: "small",
                en: { desc: "Custom scarf and textile pattern designs for MC Sarl." },
                fr: { desc: "Conception de motifs personnalisés pour foulards et textiles chez MC Sarl." },
                tools: ["CorelDraw"],
            },
            {
                name: "Corporate Flyers",
                nameFr: "Flyers Corporate",
                gradient: "linear-gradient(135deg, #0a1a2e 0%, #1a2e4d 50%, #2e4d7c 100%)",
                size: "small",
                en: { desc: "Marketing flyers and brochures for various clients." },
                fr: { desc: "Flyers marketing et brochures pour divers clients." },
                tools: ["CorelDraw","Photoshop"],
            },
        ],
    },
]

// ============================================================
// DICTIONARY
// ============================================================
export const dictionary = {
    en: {
        nav: {
            home: "About",
            skills: "Skills",
            roadmap: "Experience",
            contact: "Contact",
            portfolio: "Portfolio",
            philosophy: "Philosophy",
            studio: "Studio",
            connect: "Connect",
        },
        hero: {
            engineer: {
                eyebrow: "SOFTWARE_ENGINEER",
                title: "> Backend_Specialist \n& Mobile_Developer",
                description: "Precision engineering for scalable digital infrastructures. I bridge the gap between complex logic and minimalist design.",
                cta1: "view.projects()",
                cta2: "contact.me.init()",
            },
            designer: {
                eyebrow: "MINIMALIST_DESIGNER",
                title: "Crafting Visual\nIdentities & Digital\nExperiences.",
                description: "High-end minimalist graphic design and creative direction for brands that value aesthetic precision and functional elegance.",
                cta1: "Explore Gallery",
                cta2: "Design Ethos",
            },
            downloadCv: "Download CV"
        },
        skills: {
            title: "01. CORE_TECH_STACK",
            designTitle: "DESIGN CAPABILITIES",
            subtitle: "A hybrid skillset bridging the gap between functional code and aesthetic design.",
            designSubtitle: "Merging engineering logic with artistic intuition to create digital products that are as robust as they are beautiful.",
            categories: { frontend: "Frontend & UI", backend: "Backend Engineering", mobile: "Mobile Development", design: "Design Tools", devops: "DevOps & Tools" },
            designCapabilities: [
                { num: "01", title: "VISUAL STRATEGY", desc: "Defining the soul of a brand through rigorous exploration" },
                { num: "02", title: "DESIGN SYSTEMS", desc: "Atomic component libraries for scalable and consistent experiences" },
                { num: "03", title: "MOTION DESIGN", desc: "Adding life and narrative to static interfaces" },
            ]
        },
        experience: {
            title: "02. PROF_EXPERIENCE",
            formationTitle: "03. FORMATION",
            subtitle: "My professional journey.",
            jobs: [
                { year: "2023 — PRESENT", role: "IT Manager / Graphic Designer", company: "MC Sarl", companyColor: "#3b82f6", type: "pro", description: ["Built a complete ERP for textile production (Laravel 12 + React + PostgreSQL).", "Developed commercial management module (CodeIgniter 4).", "Managed all IT infrastructure, servers and graphic design operations.", "Designed brand identities, event posters and marketing materials."] },
                { year: "2022", role: "Full-Stack Developer (Internship)", company: "Hôpital Général de Douala", companyColor: "#10b981", type: "pro", description: ["Developed MC IMMO — asset management system for the hospital.", "PHP + MySQL stack, deployed on hospital's internal network.", "Trained staff on system usage and maintenance."] },
                { year: "2021", role: "Mobile Developer (Internship)", company: "Freelance", companyColor: "#f59e0b", type: "pro", description: ["Built Mon Compagnon Scolaire — Flutter mobile app for students.", "Designed and developed the PHP REST API backend.", "Published on Google Play Store."] },
            ],
            education: [
                { year: "2024 — Present", role: "Engineering Diploma — Software Engineering", company: "ENSPD, Douala", companyColor: "#a855f7", type: "edu", description: ["Advanced software architecture and system design.", "Research in AI, cloud computing and mobile development.", "President of the Git Club — organized SIE 2026 event."] },
                { year: "2021 — 2023", role: "Technology Degree — Software Engineering", company: "IUT Ngaoundéré", companyColor: "#6366f1", type: "edu", description: ["Web development, databases, algorithms and networks.", "Final project: academic resource management system."] },
                { year: "2019 — 2021", role: "University Technology Diploma — Computer Science", company: "IUT Ngaoundéré", companyColor: "#8b5cf6", type: "edu", description: ["Fundamentals of computer science, programming and systems."] },
                { year: "2018 — 2019", role: "Baccalauréat Série C", company: "Lycée Classique de Ngaoundéré", companyColor: "#64748b", type: "edu", description: ["Mathematics, Physics and Computer Science specialization."] },
            ]
        },
        projects: {
            title: "03. PROJECT_ARCHIVE",
            designTitle: "FEATURED WORK",
            viewAll: "View all →",
            backToProjects: "Back to projects",
            archiveTitle: "PROJECT_ARCHIVE",
            archiveSubtitle: "All projects, experiments and open-source contributions.",
            overview: "Overview",
            features: "Features",
            challenge: "Challenge",
            viewProject: "View Project",
            items: projects.map(p => ({ slug: p.slug, name: p.name, desc: p.en.desc, tags: p.tags, status: p.status, link: `/projects/${p.slug}` }))
        },
        design: {
            title: "GRAPHIC DESIGN GALLERY",
            subtitle: "Visual creations organized by theme — branding, interfaces, print and more.",
            all: "All",
            viewWork: "View work",
        },
        about: {
            title: "About Me",
            role: "Software Engineer & Graphic Designer",
            school: "Student Engineer @ ENSPD · Douala, Cameroon",
            bio: "I'm Alain Pascal LINJOUOM, a hybrid Software Engineer and Graphic Designer based in Douala, Cameroon. Currently pursuing my engineering degree in Software Engineering at ENSPD, I combine technical precision with creative vision to build digital products that are both robust and beautiful.\n\nAs IT Manager at MC Sarl, I lead the development of a complete ERP system while also handling all graphic design operations — from brand identities to UI/UX design. This dual role perfectly reflects my philosophy: technology and design are not opposites, they are two sides of the same coin.",
            s: "Technical Skills",
            education: "Education",
            interests: "Interests",
            downloadCv: "Download CV",
            contactMe: "Contact Me",
            educationItems: [
                { year: "2024 — Present", degree: "Engineering Diploma — Software Engineering", school: "ENSPD, Douala" },
                { year: "2021 — 2023", degree: "Technology Degree — Software Engineering", school: "IUT Ngaoundéré" },
                { year: "2019 — 2021", degree: "University Technology Diploma — Computer Science", school: "IUT Ngaoundéré" },
                { year: "2018 — 2019", degree: "Baccalauréat Série C", school: "Lycée Classique et Moderne de Ngaoundéré" },
            ],
            interestItems: ["Tech & Innovation", "Football", "Cinema", "Open Source", "AI & Machine Learning"],
            techSkills: [
                { name: "Laravel / PHP", level: 90 },
                { name: "React / Next.js", level: 50 },
                { name: "Flutter / Dart", level: 65 },
                { name: "Python / Django Rest Framework", level: 70 },
                { name: "Figma / UI Design", level: 65 },
                { name: "Photoshop / Illustrator", level: 65 },
                { name: "CorelDraw", level: 95 },
            ],
        },
        contact: {
            title: "Let's Connect",
            subtitle: "Ready to start your next project? Drop a line.",
            touch: "Get in touch",
            description: "I'm always open to discussing new projects, creative ideas or opportunities to be part of your visions.",
            placeholders: { name: "Name", email: "Email", subject: "Subject", message: "Message", send: "Send Message" }
        },
        footer: {
            rights: "All rights reserved.",
            status: " ",
        }
    },
    fr: {
        nav: {
            home: "À propos",
            skills: "Compétences",
            roadmap: "Expérience",
            contact: "Contact",
            portfolio: "Portfolio",
            philosophy: "Philosophie",
            studio: "Studio",
            connect: "Contact",
        },
        hero: {
            engineer: {
                eyebrow: "INGENIEUR_LOGICIEL",
                title: "> Spécialiste_Backend\n& Developpeur_Mobile",
                description: "Ingénierie de précision pour des infrastructures numériques évolutives. Je fais le lien entre la logique complexe et le design minimaliste.",
                cta1: "voir.projets()",
                cta2: "contact.init()",
            },
            designer: {
                eyebrow: "DESIGNER MINIMALISTE",
                title: "Créer des Identités\nVisuelles & Expériences\nDigitales.",
                description: "Design graphique minimaliste haut de gamme et direction créative pour des marques qui valorisent la précision esthétique.",
                cta1: "Explorer Galerie",
                cta2: "Éthique Design",
            },
            downloadCv: "Télécharger CV"
        },
        skills: {
            title: "01. STACK_TECHNIQUE",
            designTitle: "CAPACITÉS DESIGN",
            subtitle: "Des compétences hybrides reliant le code fonctionnel au design esthétique.",
            designSubtitle: "Fusionner la logique d'ingénierie avec l'intuition artistique pour créer des produits numériques aussi robustes que beaux.",
            categories: { frontend: "Frontend & UI", backend: "Ingénierie Backend", mobile: "Développement Mobile", design: "Outils de Design", devops: "DevOps & Outils" },
            designCapabilities: [
                { num: "01", title: "STRATÉGIE VISUELLE", desc: "Définir l'âme d'une marque par une exploration rigoureuse" },
                { num: "02", title: "SYSTÈMES DE DESIGN", desc: "Bibliothèques de composants atomiques pour des expériences cohérentes" },
                { num: "03", title: "MOTION DESIGN", desc: "Ajouter vie et narration aux interfaces statiques" },
            ]
        },
        experience: {
            title: "02. EXPÉRIENCE_PROF",
            formationTitle: "03. FORMATION",
            subtitle: "Mon parcours professionnel.",
            jobs: [
                { year: "2025 — PRÉSENT", role: "Responsable Informatique / Infographe", company: "MC Sarl", companyColor: "#3b82f6", type: "pro", description: ["Création d'un ERP complet pour la production textile (Laravel 12 + React + PostgreSQL).", "Développement du module de gestion commerciale (CodeIgniter 4).", "Gestion de toute l'infrastructure IT, serveurs et opérations de design graphique.", "Conception d'identités de marque, affiches événementielles et supports marketing."] },
                { year: "2024", role: "Développeur Full-Stack (Stage)", company: "Hôpital Général de Douala", companyColor: "#10b981", type: "pro", description: ["Développement de MC IMMO — système de gestion du patrimoine hospitalier.", "Stack PHP + MySQL, déployé sur le réseau interne de l'hôpital.", "Formation du personnel à l'utilisation et à la maintenance du système."] },
                { year: "2023", role: "Développeur Mobile (Stage)", company: "Freelance", companyColor: "#f59e0b", type: "pro", description: ["Création de Mon Compagnon Scolaire — application mobile Flutter pour étudiants.", "Conception et développement de l'API REST PHP backend.", "Publication sur le Google Play Store."] },
            ],
            education: [
                { year: "2024 — Présent", role: "Diplôme d'Ingénieur — Génie Logiciel", company: "ENSPD, Douala", companyColor: "#a855f7", type: "edu", description: ["Architecture logicielle avancée et conception système.", "Recherche en IA, cloud computing et développement mobile.", "Président du Club Git — organisation de la SIE 2026."] },
                { year: "2021 — 2023", role: "Licence Technologique — Génie Logiciel", company: "IUT Ngaoundéré", companyColor: "#6366f1", type: "edu", description: ["Développement web, bases de données, algorithmes et réseaux.", "Projet de fin d'études : système de gestion de ressources académiques."] },
                { year: "2019 — 2021", role: "DUT — Informatique", company: "IUT Ngaoundéré", companyColor: "#8b5cf6", type: "edu", description: ["Fondamentaux de l'informatique, programmation et systèmes."] },
                { year: "2018 — 2019", role: "Baccalauréat Série C", company: "Lycée Classique de Ngaoundéré", companyColor: "#64748b", type: "edu", description: ["Spécialisation Mathématiques, Physique et Informatique."] },
            ]
        },
        projects: {
            title: "03. ARCHIVE_PROJETS",
            designTitle: "TRAVAUX SÉLECTIONNÉS",
            viewAll: "Voir tout →",
            backToProjects: "Retour aux projets",
            archiveTitle: "ARCHIVE_PROJETS",
            archiveSubtitle: "Tous les projets, expériences et contributions open-source.",
            overview: "Aperçu",
            features: "Fonctionnalités",
            challenge: "Défi",
            viewProject: "Voir le projet",
            items: projects.map(p => ({ slug: p.slug, name: p.name, desc: p.fr.desc, tags: p.tags, status: p.status, link: `/projects/${p.slug}` }))
        },
        design: {
            title: "GALERIE DESIGN GRAPHIQUE",
            subtitle: "Créations visuelles organisées par thème — branding, interfaces, print et plus.",
            all: "Tout",
            viewWork: "Voir le travail",
        },
        about: {
            title: "À propos",
            role: "Ingénieur Logiciel & Designer Graphique",
            school: "Élève Ingénieur @ ENSPD · Douala, Cameroun",
            bio: "Je suis Alain Pascal LINJOUOM, un ingénieur logiciel et designer graphique hybride basé à Douala, au Cameroun. Actuellement en formation d'ingénieur en Génie Logiciel à l'ENSPD, je combine précision technique et vision créative pour construire des produits numériques à la fois robustes et beaux.\n\nEn tant que Responsable Informatique chez MC Sarl, je dirige le développement d'un système ERP complet tout en gérant toutes les opérations de design graphique — des identités de marque au design UI/UX. Ce double rôle reflète parfaitement ma philosophie : la technologie et le design ne sont pas des opposés, ce sont deux faces d'une même pièce.",
            skills: "Compétences Techniques",
            education: "Formation",
            interests: "Centres d'intérêt",
            downloadCv: "Télécharger CV",
            contactMe: "Me Contacter",
            educationItems: [
                { year: "2024 — Présent", degree: "Diplôme d'Ingénieur — Génie Logiciel", school: "ENSPD, Douala" },
                { year: "2021 — 2023", degree: "Licence Technologique — Génie Logiciel", school: "IUT Ngaoundéré" },
                { year: "2019 — 2021", degree: "DUT — Informatique", school: "IUT Ngaoundéré" },
                { year: "2018 — 2019", degree: "Baccalauréat Série C", school: "Lycée Classique et Moderne de Ngaoundéré" },
            ],
            interestItems: ["Tech & Innovation", "Football", "Cinéma", "Open Source", "IA & Machine Learning"],
            techSkills: [
                { name: "Laravel / PHP", level: 90 },
                { name: "React / Next.js", level: 50 },
                { name: "Flutter / Dart", level: 65 },
                { name: "Python / Django Rest Framework", level: 70 },
                { name: "Figma / UI Design", level: 65 },
                { name: "Photoshop / Illustrator", level: 65 },
                { name: "CorelDraw", level: 90 },
            ],
        },
        contact: {
            title: "Restons Connectés",
            subtitle: "Prêt à démarrer votre prochain projet ? Écrivez-moi.",
            touch: "Contactez-moi",
            description: "Toujours ouvert à la discussion pour de nouveaux projets, idées créatives ou opportunités de collaboration.",
            placeholders: { name: "Nom", email: "Email", subject: "Sujet", message: "Message", send: "Envoyer" }
        },
        footer: {
            rights: "Tous droits réservés.",
            status: " ",
        }
    }
}
